spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capston?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cho980625
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:mysql:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username:
#    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        #???? ??? /* ??? ??? ????.
        use_sql_comments : true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 889484100500-deajo3p9rv1d4hl09fl2rok9krl45cbk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging.level:
  org.hibernate.SQL: debug

