spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capston?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cho980625
    driver-class-name: com.mysql.cj.jdbc.Driver